apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- end }}
  # 透過 range 處理的資料可以來自於 Values 物件
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings1 }}
    - {{ . | title | quote }}
    {{- end }}
  # 也可以直接定義在 template 中
  sizes: |-
    {{- range tuple "small" "medium" "large" }}
    - {{ . }}
    {{- end }}